import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  {
    id: 0.25,
    name: "Client",
    href: "#",
    image: "/images/brand/facebook.png",
    imageLight: "/images/brand/facebook.png",
  },
  {
    id: 0.3,
    name: "Client",
    href: "#",
    image: "/images/brand/zapier.png",
    imageLight: "/images/brand/zapier.png",
  },
  {
    id: 0.4,
    name: "Client",
    href: "#",
    image: "/images/brand/what.png",
    imageLight: "/images/brand/what.png",
  },
  {
    id: 0.5,
    name: "Client",
    href: "#",
    image: "/images/brand/instagram.png",
    imageLight: "/images/brand/instagram.png",
  },
  {
    id: 0.6,
    name: "Client",
    href: "#",
    image: "/images/brand/indiamart.png",
    imageLight: "/images/brand/indiamart.png",
  },
  {
    id: 0.7,
    name: "Client",
    href: "#",
    image: "/images/brand/magikbrics.png",
    imageLight: "/images/brand/magikbrics.png",
  },
  {
    id: 0.8,
    name: "Client",
    href: "#",
    image: "/images/brand/99acress.png",
    imageLight: "/images/brand/99acress.png",
  },
  {
    id: 0.9,
    name: "Client",
    href: "#",
    image: "/images/brand/wix-1.png",
    imageLight: "/images/brand/wix-1.png",
  },
  {
    id: 0.10,
    name: "Client",
    href: "#",
    image: "/images/brand/hub.png",
    imageLight: "/images/brand/hub.png",
  },
  {
    id: 0.11,
    name: "Client",
    href: "#",
    image: "/images/brand/Just-Dial.png",
    imageLight: "/images/brand/Just-Dial.png",
  },
  {
    id: 0.12,
    name: "Client",
    href: "#",
    image: "/images/brand/proactivesms.png",
    imageLight: "/images/brand/proactivesms.png",
  },
  {
    id: 0.13,
    name: "Client",
    href: "#",
    image: "/images/brand/telecmi.png",
    imageLight: "/images/brand/telecmi.png",
  },
  {
    id: 0.14,
    name: "Client",
    href: "#",
    image: "/images/brand/iftt.png",
    imageLight: "/images/brand/iftt.png",
  },
  {
    id: 0.15,
    name: "Client",
    href: "#",
    image: "/images/brand/integramt.png",
    imageLight: "/images/brand/integramt.png",
  },
  {
    id: 0.16,
    name: "Client",
    href: "#",
    image: "/images/brand/g-shet.png",
    imageLight: "/images/brand/g-shet.png",
  },
];

export default brandData;